name: compile
on: [ push ]
  # push:
  #   branch: 
  #     - master
  #   paths:
  #     - 'src/**'
  #     - '.github/workflow/**'

jobs: 
  build: 
    strategy: 
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x86_64-unknown-linux-gnu
          - os: windows-latest
            triplet: x86_64-pc-windows-msvc

    name: ${{ matrix.os }} - ${{ matrix.triplet }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360 # default
    # env:
    steps:
        
        # https://github.com/actions/setup-node

        # region dump
      - name: Dump Github Context
        env:
          GITHUB_CONTEXT: ${{ toJSON( github ) }}
        run: echo "$GITHUB_CONTEXT"
        # endregion 
        #region checkout
        # 
      - name: Checkout Code
        uses: actions/checkout@v2
        #endregion
        #region tool chain
        # https://github.com/actions-rs/toolchain
      - name: Set Toolchain
        id: setToolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.triplet }}
          default: true
      - name: debug toolchain
        env:
          TOOLCHAIN_OUTPUT: ${{ toJSON( steps.setToolchain.outputs ) }}
        run: echo "$TOOLCHAIN_OUTPUT"
        #endregion

        # https://github.com/actions-rs/cargo
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.triplet }}
        
        # https://github.com/actions/cache
        
        # https://github.com/marketplace/actions/easy-zip-files
      - name: Zip
        uses: papeloto/action-zip@v1
        with: 
          files: target/${{ matrix.triplet }}
          dest: target/${{ matrix.triplet }}.zip

        # https://github.com/actions/create-release
        - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}-${{ matrix.os }}-${{ matrix.triplet }}-${{ github.run_number }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: true
        
        # https://github.com/actions/upload-release-asset
      - name: Upload Release
        id: updload_release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/${{ matrix.triplet }}.zip
          asset_name: glowing-tribble.zip
          asset_content_type: application/zip

      - name: Update Downloads
        env: 
          DOWNLOAD_URL: ${{ steps.upload_release.outputs.browser_download_url }} 
        run: echo "$DOWNLOAD_URL"

      # fml its not triggering