name: compile
on: 
  push:
    branch: 
      - master
    paths:
      - 'src/**'

jobs: 
  build: 
    strategy: 
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x86_64-unknown-linux-gnu
          - os: windows-latest
            triplet: x86_64-pc-windows-msvc

    name: ${{ matrix.os }} - ${{ matrix.triplet }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360 # default
    fail-fast: false
    # env:
    steps:

      - name: Dump Github Context
        env:
          GITHUB_CONTEXT: ${{ toJSON( github ) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build
        run: |
          cargo build --target ${{ matrix.triplet }}
          zip ./target/${{ target.triplet }} REAME.md
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: true

      - name: Upload Release
        id: updload_release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/${{ matrix.triplet }}.zip
          asset_name: glowing-tribble.zip
          asset_content_type: application/zip

      - name: Update Downloads
          env: 
            DOWNLOAD_URL: ${{ steps.upload_release.outputs.browser_download_url }} 
        run: echo "$DOWNLOAD_URL"
        
