name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      # everything here is just trying to fix build issues in vm
    - name: Apt Install
      run: |
        sudo apt install gcc pkg-config openssl libasound2-dev cmake build-essential python3 libfreetype6-dev libexpat1-dev libxcb-composite0-dev libssl-dev libx11-dev libfontconfig1-dev
      

    - run: git config --global init.defaultBranch master
    - uses: actions/checkout@v2

    - run: rustup default nightly
    - run: rustup set profile minimal
    - run: rustup target add x86_64-unknown-linux-gnu
    - run: rustup target add x86_64-pc-windows-gnu
    - run: rustup show

    - run: cargo install cross
    
    - name: Build x86_64-unknown-linux-gnu --verbose --jobs 1
      run: cargo build --target=x86_64-unknown-linux-gnu --release
    - name: Build x86_64-pc-windows-gnu --verbose --jobs 1
      run: cross build --target=x86_64-pc-windows-gnu --release

    - name: Cache Dependencies
      uses: actions/cache@v2
      with: 
        path: |
          ~/.cargo/registery
          ~/.cargo/git
          ./target/x86_64-unknown-linux-gnu
          ./target/x86_64-pc-windows-gnu
        key: ${{ runner.os }}-cargo-${{ hashFiles( '**/Cargo.lock' ) }}

    - name: Zip binaries with assets
      run: |
        mv ./target/x86_64-unknown-linux-gnu/release/glowing-tribble .
        zip -r x86_64-unknown-linux-gnu.zip ./glowing-tribble ./assets ./config
        mv ./target/x86_64-pc-windows-gnu/release/glowing-tribble .
        zip -r x86_64-pc-windows-gnu.zip ./glowing-tribble ./assets ./config

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}-${{ github.run_number }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: true

    - name: Upload Release
      id: updload_release_x86_64-unknown-linux-gnu
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: x86_64-unknown-linux-gnu.zip
        asset_name: x86_64-unknown-linux-gnu.zip
        asset_content_type: application/zip

    - name: Upload Release
      id: updload_release_x86_64-pc-windows-gnu
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: x86_64-pc-windows-gnu.zip
        asset_name: x86_64-pc-windows-gnu.zip
        asset_content_type: application/zip

    - run: echo "${{ steps.updload_release_x86_64-unknown-linux-gnu.browser_download_url }} ${{ steps.updload_release_x86_64-pc-windows-gnu.browser_download_url }}" > ./page/releases.json

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: page
        CLEAN: true
