name: windows
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    name: (${{ matrix.target }}, ${{ matrix.channel }})
    strategy:
      # https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits
      # There's a limit of 60 concurrent jobs across all repos in the rust-lang organization.
      # In order to prevent overusing too much of that 60 limit, we throttle the
      # number of rustfmt jobs that will run concurrently.
      max-parallel: 2
      fail-fast: false
      matrix:
        target: [
          # i686-pc-windows-gnu,
          # Running `D:\a\glowing-tribble\glowing-tribble\target\debug\build\gfx-backend-metal-34b8e8cb0833ebeb\build-script-build`
          # error: failed to run custom build command for `gfx-backend-metal v0.3.3`
          # Caused by:
          #   process didn't exit successfully: `D:\a\glowing-tribble\glowing-tribble\target\debug\build\gfx-backend-metal-34b8e8cb0833ebeb\build-script-build` (exit code: 101)
          #   --- stderr
          # thread 'main' panicked at 'unsupported target i686-pc-windows-gnu', C:\Users\runneradmin\.cargo\registry\src\github.com-1285ae84e5963aae\gfx-backend-metal-0.3.3\build.rs:17:9
          
          # i686-pc-windows-msvc,     
          # Running `D:\a\glowing-tribble\glowing-tribble\target\debug\build\gfx-backend-metal-4315de4833fbb566\build-script-build`
          # error: failed to run custom build command for `gfx-backend-metal v0.3.3`
          # Caused by:
          #   process didn't exit successfully: `D:\a\glowing-tribble\glowing-tribble\target\debug\build\gfx-backend-metal-4315de4833fbb566\build-script-build` (exit code: 101)
          # --- stderr
          # thread 'main' panicked at 'unsupported target i686-pc-windows-msvc', C:\Users\runneradmin\.cargo\registry\src\github.com-1285ae84e5963aae\gfx-backend-metal-0.3.3\build.rs:17:9

          # x86_64-pc-windows-gnu,
          # Running `D:\a\glowing-tribble\glowing-tribble\target\debug\build\gfx-backend-metal-7605353f0391bda5\build-script-build`
          # error: failed to run custom build command for `gfx-backend-metal v0.3.3`
          # Caused by:
          #   process didn't exit successfully: `D:\a\glowing-tribble\glowing-tribble\target\debug\build\gfx-backend-metal-7605353f0391bda5\build-script-build` (exit code: 101)
          # --- stderr
          # thread 'main' panicked at 'unsupported target x86_64-pc-windows-gnu', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-metal-0.3.3\build.rs:17:9

          # x86_64-pc-windows-msvc,
          # Running `D:\a\glowing-tribble\glowing-tribble\target\debug\build\gfx-backend-metal-702024b54cbbe194\build-script-build`
          # error: failed to run custom build command for `gfx-backend-metal v0.3.3`
          # Caused by:
          #   process didn't exit successfully: `D:\a\glowing-tribble\glowing-tribble\target\debug\build\gfx-backend-metal-702024b54cbbe194\build-script-build` (exit code: 101)
          # --- stderr
          # thread 'main' panicked at 'unsupported target x86_64-pc-windows-msvc', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-metal-0.3.3\build.rs:17:9

        ]
        channel: [ nightly ]
        include:
          - channel: nightly
            target: i686-pc-windows-gnu

    env:
      CFG_RELEASE_CHANNEL: nightly
      CFG_RELEASE: nightly

    steps:
    # The Windows runners have autocrlf enabled by default
    # which causes failures for some of rustfmt's line-ending sensitive tests
    - name: disable git eol translation
      run: git config --global core.autocrlf false
    - name: checkout
      uses: actions/checkout@v2

      # Run build
    - name: setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.channel }}-${{ matrix.target }}
        target: ${{ matrix.target }}
        override: true
        profile: minimal
        default: true

    - name: Add mingw32 to path for i686-gnu
      run: |
        echo "C:\msys64\mingw32\bin" >> $GITHUB_PATH
      if: matrix.target == 'i686-pc-windows-gnu' && matrix.channel == 'nightly'
      shell: bash

    - name: Add mingw64 to path for x86_64-gnu
      run: echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
      if: matrix.target == 'x86_64-pc-windows-gnu' && matrix.channel == 'nightly'
      shell: bash

    - name: cargo-make
      run: cargo install --force cargo-make

    - name: build
      run: |
        rustc -Vv
        cargo -V
        cargo make build
      shell: cmd

    - name: test
      run: cargo make test
      shell: cmd